name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace 'main' with your default branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy app content to dist folder
      run: mkdir -p dist && cp -r app/* dist/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub-provided token
        publish_branch: main # The branch to deploy to
        publish_dir: dist # The directory to publish
